name = "Hermits Hearth"
author = "Waveformal (Base pack by Xisumavoid)"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c0bba8e76fbebe2b5e90c4dc21fbeed4f1b0ba6b5faab9bdd292f3c9432adcd"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
