name = "Hermits Hearth"
author = "Waveformal (Base pack by Xisumavoid)"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "23a0057bfb2d01a0d2675b0dabd161146f8bb3ca9f6c8e8f857f722c460dcfd8"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
