name = "Hermits Hearth"
author = "Waveformal (Base pack by Xisumavoid)"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "58146088118948d97df1c702ecd9d15a3a50fbe28ff303ea03a0e54150111c23"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
